parameters:
  assetic.compass.class: "Majisti\UtilsBundle\Assetic\Filter\Sass\CompassFilter"
  assetic.compass.compass_path: "/usr/bin/compass"
  assetic.compass.load_path: "%kernel.root_dir%/../vendor/bundles/Majisti/UtilsBundle/Resources/scss"
  assetic.compass.http_path: ".."

services:
  compass:
    class:     %assetic.compass.class%
    arguments: [%assetic.compass.compass_path%]
    calls:
      - [ "setImagesDir", [ %assetic.compass.images_dir% ] ]
      - [ "setHttpPath", [ %assetic.compass.http_path% ] ]
      - [ "addLoadPath", [ %assetic.compass.load_path ]]
    tags:
      - { name: assetic.filter, alias: compass }